import type {
  LibraryEntry,
  Crop,
  RiskAlert,
  AppNotification,
  ScanResult,
  NotificationType,
  AlertType,
  RiskLevel,
  Severity,
} from '../types';

// Deterministic demo dataset. Used only when DEMO_MODE=true.
// Clearly labelled as demo data everywhere it is surfaced.

let counter = 0;
export function demoId(prefix: string): string {
  counter += 1;
  return `${prefix}_${String(counter).padStart(4, '0')}`;
}

function iso(daysAgo: number, hour = 9): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export const DEMO_USER_ID = demoId('usr');

const DEMO_LIBRARY: LibraryEntry[] = [
  {
    id: demoId('dis'),
    name: 'Early Blight',
    cropName: 'Tomato',
    kind: 'DISEASE',
    description:
      'A fungal disease that appears first on older leaves as small brown spots with concentric rings. It spreads quickly in warm, humid weather and can defoliate plants if unmanaged.',
    symptoms: [
      'Brown spots with concentric rings on lower leaves',
      'Yellowing around spots, leaves dry and drop',
      'Dark sunken lesions on stems near soil line',
    ],
    causes: ['Fungus Alternaria solani', 'Warm temperatures between 20 and 30 C', 'Long leaf wetness from dew or splashing rain'],
    favorable: ['High humidity above 80 percent', 'Recent rainfall', 'Poor air circulation in dense canopy'],
    prevention: ['Use certified disease-free seed', 'Rotate with non-solanaceous crops for 2 to 3 seasons', 'Ensure proper plant spacing for airflow', 'Avoid overhead irrigation in the evening'],
    management: [
      'Remove and destroy visibly infected leaves',
      'Monitor the crop every 3 to 4 days',
      'If disease spreads, consult a local agriculture officer before any fungicide use and follow the product label exactly',
    ],
    severity: 'MODERATE',
    isActive: true,
    createdAt: iso(90),
    updatedAt: iso(5),
  },
  {
    id: demoId('dis'),
    name: 'Late Blight',
    cropName: 'Tomato',
    kind: 'DISEASE',
    description:
      'A highly destructive water mould disease that can destroy a tomato crop within days under cool, wet conditions. Lesions appear water-soaked and grow rapidly.',
    symptoms: [
      'Greasy water-soaked patches on leaves',
      'White fungal growth on leaf undersides in humid weather',
      'Brown streaks on stems, fruit rot with firm dark patches',
    ],
    causes: ['Water mould Phytophthora infestans', 'Cool nights and wet foliage', 'Infected volunteer plants or nearby potato crops'],
    favorable: ['Cool temperatures between 10 and 22 C', 'High humidity and frequent rain', 'Dense unpruned canopy'],
    prevention: ['Plant resistant varieties where available', 'Keep wider plant spacing', 'Scout fields weekly in cool wet periods', 'Remove volunteer tomato and potato plants'],
    management: [
      'Destroy infected plants early to slow spread',
      'Improve drainage and reduce leaf wetness',
      'Contact your local Krishi Vigyan Kendra for region-specific guidance before any chemical treatment',
    ],
    severity: 'HIGH',
    isActive: true,
    createdAt: iso(90),
    updatedAt: iso(5),
  },
  {
    id: demoId('dis'),
    name: 'Blast',
    cropName: 'Rice',
    kind: 'DISEASE',
    description:
      'One of the most damaging rice diseases, caused by a fungus. It affects leaves, nodes and panicles, appearing as eye-shaped spots with grey centres.',
    symptoms: [
      'Diamond-shaped spots with grey centres and brown margins on leaves',
      'Nodes turn black and break',
      'Panicles dry partially or fully and grains remain empty',
    ],
    causes: ['Fungus Magnaporthe oryzae', 'Extended periods of leaf wetness', 'Excess nitrogen fertilisation'],
    favorable: ['High humidity above 90 percent', 'Cool cloudy weather with dew', 'Dense crop with heavy nitrogen'],
    prevention: ['Use recommended seed treatment', 'Avoid excess nitrogen fertiliser', 'Maintain proper plant spacing', 'Use blast-tolerant varieties for the region'],
    management: [
      'Drain excess standing water where practical',
      'Monitor panicle stage closely, it is the most vulnerable stage',
      'Seek guidance from the local agriculture extension officer before any fungicide application',
    ],
    severity: 'HIGH',
    isActive: true,
    createdAt: iso(90),
    updatedAt: iso(5),
  },
  {
    id: demoId('dis'),
    name: 'Bacterial Leaf Blight',
    cropName: 'Rice',
    kind: 'DISEASE',
    description:
      'A bacterial disease that causes long yellow to white lesions along leaf margins, usually after heavy rain or flooding. Yields drop when leaves dry prematurely.',
    symptoms: [
      'Wavy yellow lesions starting at leaf margins',
      'Leaves dry out from tip downward',
      'Milky droplets of bacterial ooze on young lesions',
    ],
    causes: ['Bacterium Xanthomonas oryzae', 'Entry through wounds and water pores', 'Spread by rain splash and infected stubble'],
    favorable: ['Heavy rain and storms', 'Warm temperatures around 25 to 30 C', 'High nitrogen and dense planting'],
    prevention: ['Use disease-free certified seed', 'Avoid wounding plants during weeding', 'Balance nitrogen use', 'Drain fields during prolonged flooding where possible'],
    management: [
      'Remove and burn infected stubble after harvest',
      'Keep the field well drained',
      'Copper-based sprays are sometimes used; consult the local agriculture officer and follow the product label',
    ],
    severity: 'HIGH',
    isActive: true,
    createdAt: iso(90),
    updatedAt: iso(5),
  },
  {
    id: demoId('dis'),
    name: 'Leaf Spot',
    cropName: 'Cotton',
    kind: 'DISEASE',
    description:
      'Alternaria leaf spot of cotton begins as small dark spots that enlarge with yellow halos. Severe infection causes premature defoliation and boll quality loss.',
    symptoms: [
      'Small dark brown spots with yellow halos',
      'Spots merge and leaves drop early',
      'Infection on bracts near bolls in wet weather',
    ],
    causes: ['Fungus Alternaria macrospora', 'Nutrient stress, especially low potassium', 'Humid wet weather'],
    favorable: ['Humidity above 80 percent', 'Continuous rain for several days', 'Stressed or aging crop'],
    prevention: ['Maintain balanced nutrition, especially potassium', 'Avoid overhead irrigation', 'Remove crop debris after harvest', 'Choose well-drained fields'],
    management: [
      'Improve airflow by managing dense canopy growth',
      'Continue balanced fertilisation to reduce plant stress',
      'Ask the local extension officer about suitable options and always follow the product label',
    ],
    severity: 'MODERATE',
    isActive: true,
    createdAt: iso(90),
    updatedAt: iso(5),
  },
  {
    id: demoId('pes'),
    name: 'Aphids',
    cropName: 'Tomato',
    kind: 'PEST',
    description:
      'Small soft-bodied insects that cluster on young shoots and the underside of leaves, sucking sap and spreading viruses. They reproduce very quickly.',
    symptoms: ['Curled young leaves and sticky honeydew', 'Clusters of small green, black or grey insects on shoots', 'Sooty mould growing on honeydew'],
    causes: ['Sap-sucking colonies on tender growth', 'Excess nitrogen encouraging lush shoots', 'Natural predators reduced by broad spraying'],
    favorable: ['Warm dry weather', 'Lush new plant growth', 'Weedy field borders hosting colonies'],
    prevention: ['Inspect undersides of young leaves weekly', 'Encourage ladybird beetles and other natural enemies', 'Remove weeds around the field', 'Avoid excess nitrogen'],
    management: [
      'Spray with water to knock down small colonies',
      'Release or conserve natural predators where possible',
      'Use yellow sticky traps to monitor population',
      'If populations keep rising, consult the local agriculture officer and follow any product label exactly',
    ],
    severity: 'MODERATE',
    isActive: true,
    createdAt: iso(90),
    updatedAt: iso(5),
  },
  {
    id: demoId('pes'),
    name: 'Whitefly',
    cropName: 'Tomato',
    kind: 'PEST',
    description:
      'Tiny white flying insects found in swarms under leaves. They suck sap, excrete honeydew and transmit damaging viruses such as tomato leaf curl.',
    symptoms: ['Tiny white insects fly up when leaves are disturbed', 'Yellowing leaves with sticky coating', 'Upward leaf curling suggesting virus spread'],
    causes: ['Sap-sucking adults and nymphs under leaves', 'Warm dry conditions', 'Alternative host weeds nearby'],
    favorable: ['Dry warm weather', 'Dense continuous cropping', 'Weedy hosts around fields'],
    prevention: ['Use yellow sticky traps at canopy height', 'Cover nurseries with fine insect-proof net', 'Remove host weeds', 'Avoid planting new crops next to heavily infested fields'],
    management: [
      'Monitor with sticky traps and record counts',
      'Conserve natural enemies such as Encarsia wasps',
      'Rotate chemical groups only with expert guidance and always follow the product label',
    ],
    severity: 'HIGH',
    isActive: true,
    createdAt: iso(90),
    updatedAt: iso(5),
  },
  {
    id: demoId('pes'),
    name: 'Stem Borer',
    cropName: 'Rice',
    kind: 'PEST',
    description:
      'Caterpillars that bore into rice stems, cutting the growing point. Damage shows as dead hearts in the vegetative stage and empty panicles later.',
    symptoms: ['Dead central shoots that pull out easily', 'Empty panicles with white heads', 'Small exit holes on stems near nodes'],
    causes: ['Moth larvae boring into stems', 'Eggs laid on leaf tips in masses', 'Carry-over in stubble from previous season'],
    favorable: ['Warm humid weather', 'Dense closed canopy', 'Continuous rice cropping without fallow'],
    prevention: ['Remove and destroy stubble and stubble piles after harvest', 'Clip seedling tips to remove egg masses before transplanting', 'Avoid excess nitrogen', 'Use light traps to reduce moth populations'],
    management: [
      'Collect and destroy egg masses found during scouting',
      'Cut and remove dead hearts below the damage point',
      'Follow integrated pest management advice from the local extension officer before any pesticide use',
    ],
    severity: 'HIGH',
    isActive: true,
    createdAt: iso(90),
    updatedAt: iso(5),
  },
  {
    id: demoId('pes'),
    name: 'Brown Planthopper',
    cropName: 'Rice',
    kind: 'PEST',
    description:
      'Brown insects that gather at the base of rice stems and suck sap. Heavy infestation causes hopper burn, patches of dried crop that look scorched.',
    symptoms: ['Insects at the base of stems, hop to surface when disturbed', 'Oily brown patches then hopper burn at field edges', 'Sooty mould and stunted plants'],
    causes: ['Sap-sucking nymphs and adults at stem base', 'Dense canopy with high nitrogen', 'Misuse of broad-spectrum insecticides killing natural enemies'],
    favorable: ['High humidity in closed canopy', 'Heavy nitrogen fertilisation', 'Continuous flooding and still air'],
    prevention: ['Monitor weekly by sweeping at stem bases', 'Leave wider spacing to open the canopy', 'Moderate nitrogen use', 'Conserve spiders and other natural enemies'],
    management: [
      'Drain the field briefly to expose and reduce nymphs',
      'Avoid unnecessary broad-spectrum sprays',
      'Seek extension advice for area-specific integrated management and follow product labels',
    ],
    severity: 'HIGH',
    isActive: true,
    createdAt: iso(90),
    updatedAt: iso(5),
  },
  {
    id: demoId('pes'),
    name: 'Thrips',
    cropName: 'Chilli',
    kind: 'PEST',
    description:
      'Tiny slender insects that rasp leaves and flowers, causing curling, silvering and flower drop. Thrips also spread leaf curl virus in chilli.',
    symptoms: ['Curled and crinkled leaves with silvery streaks', 'Flower drop and few fruit set', 'Distorted new growth at the top of plants'],
    causes: ['Rasping-sucking adults and nymphs on flowers and leaves', 'Dry hot weather favouring buildup', 'Weedy flowering hosts nearby'],
    favorable: ['Hot dry spells', 'Sparse canopy and open flowers', 'Continuous flowering crops'],
    prevention: ['Use blue sticky traps', 'Irrigate regularly to reduce plant stress', 'Remove weeds and old infected plants', 'Cover nurseries with fine net'],
    management: [
      'Monitor traps and plant tops weekly',
      'Conserve predatory mites and bugs',
      'Consult the local agriculture officer for product choices and follow the label strictly',
    ],
    severity: 'MODERATE',
    isActive: true,
    createdAt: iso(90),
    updatedAt: iso(5),
  },
];

export const DEMO_CROPS: Crop[] = [
  {
    id: demoId('crop'),
    userId: DEMO_USER_ID,
    name: 'Tomato',
    variety: 'Arka Rakshak',
    fieldName: 'North Plot',
    areaValue: 2,
    areaUnit: 'acre',
    sowingDate: iso(75),
    harvestDate: iso(-40),
    growthStage: 'FRUITING',
    soilType: 'BLACK',
    irrigationType: 'DRIP',
    location: '12.9716,77.5946',
    fieldBoundary: null,
    healthScore: 68,
    riskLevel: 'MEDIUM',
    createdAt: iso(75),
    updatedAt: iso(1),
  },
  {
    id: demoId('crop'),
    userId: DEMO_USER_ID,
    name: 'Rice',
    variety: 'Sona Masuri',
    fieldName: 'Paddy Field 1',
    areaValue: 1.5,
    areaUnit: 'acre',
    sowingDate: iso(90),
    harvestDate: iso(-20),
    growthStage: 'FLOWERING',
    soilType: 'ALLUVIAL',
    irrigationType: 'CANAL',
    location: '12.9716,77.5946',
    fieldBoundary: null,
    healthScore: 88,
    riskLevel: 'LOW',
    createdAt: iso(90),
    updatedAt: iso(2),
  },
  {
    id: demoId('crop'),
    userId: DEMO_USER_ID,
    name: 'Chilli',
    variety: 'Byadgi',
    fieldName: 'East Plot',
    areaValue: 1,
    areaUnit: 'acre',
    sowingDate: iso(60),
    harvestDate: iso(-60),
    growthStage: 'FLOWERING',
    soilType: 'RED',
    irrigationType: 'SPRINKLER',
    location: '12.9716,77.5946',
    fieldBoundary: null,
    healthScore: 80,
    riskLevel: 'LOW',
    createdAt: iso(60),
    updatedAt: iso(3),
  },
  {
    id: demoId('crop'),
    userId: DEMO_USER_ID,
    name: 'Cotton',
    variety: 'Bollgard',
    fieldName: 'West Plot',
    areaValue: 2,
    areaUnit: 'acre',
    sowingDate: iso(100),
    harvestDate: iso(-30),
    growthStage: 'FRUITING',
    soilType: 'BLACK',
    irrigationType: 'RAINFED',
    location: '12.9716,77.5946',
    fieldBoundary: null,
    healthScore: 74,
    riskLevel: 'MEDIUM',
    createdAt: iso(100),
    updatedAt: iso(4),
  },
];

export const DEMO_ALERTS: RiskAlert[] = [
  {
    id: demoId('alt'),
    userId: DEMO_USER_ID,
    cropId: null,
    cropName: 'Tomato',
    type: 'DISEASE_RISK' as AlertType,
    riskLevel: 'HIGH' as RiskLevel,
    title: 'Fungal disease conditions detected for Tomato',
    description: 'Weather and crop stage favour fungal disease spread in your area.',
    reasons: ['High humidity above 80 percent', 'Recent rainfall in the last 48 hours', 'Fruiting stage is vulnerable to Early Blight'],
    weatherNote: 'Humidity 82 percent, 18 mm rain in 48 hours, temperature around 27 C',
    action: 'Inspect lower leaves for brown spots with rings and monitor the crop every 3 days.',
    score: 72,
    isRead: false,
    createdAt: iso(0, 7),
    updatedAt: iso(0, 7),
  },
  {
    id: demoId('alt'),
    userId: DEMO_USER_ID,
    cropId: null,
    cropName: 'Rice',
    type: 'PEST_RISK' as AlertType,
    riskLevel: 'MEDIUM' as RiskLevel,
    title: 'Stem borer activity likely in Rice',
    description: 'Moth activity rises in warm humid weather during the flowering stage.',
    reasons: ['Warm humid evenings', 'Flowering stage attracts egg laying', 'Stubble present nearby from last season'],
    weatherNote: 'Humidity 82 percent, light showers expected',
    action: 'Check for egg masses on leaf tips and remove dead hearts below the damage point.',
    score: 55,
    isRead: false,
    createdAt: iso(1, 8),
    updatedAt: iso(1, 8),
  },
  {
    id: demoId('alt'),
    userId: DEMO_USER_ID,
    cropId: null,
    cropName: null,
    type: 'WEATHER' as AlertType,
    riskLevel: 'LOW' as RiskLevel,
    title: 'Light rain expected this week',
    description: 'Light showers forecast for the next 3 days in your district.',
    reasons: ['Forecast shows 10 to 15 mm rain across 3 days'],
    weatherNote: 'Daytime temperature near 28 C',
    action: 'Plan irrigation and spraying schedules around the showers.',
    score: 30,
    isRead: true,
    createdAt: iso(2, 9),
    updatedAt: iso(2, 9),
  },
];

export const DEMO_NOTIFICATIONS: AppNotification[] = [
  {
    id: demoId('ntf'),
    userId: DEMO_USER_ID,
    type: 'DISEASE_RISK' as NotificationType,
    title: 'Disease risk alert for Tomato',
    body: 'High humidity and recent rainfall raise fungal disease risk. Inspect lower leaves.',
    link: '/alerts',
    isRead: false,
    createdAt: iso(0, 7),
  },
  {
    id: demoId('ntf'),
    userId: DEMO_USER_ID,
    type: 'CROP_REMINDER' as NotificationType,
    title: 'Crop reminder: Rice flowering stage',
    body: 'Rice is entering flowering. Scout for stem borer egg masses on leaf tips.',
    link: '/crops',
    isRead: false,
    createdAt: iso(1, 8),
  },
  {
    id: demoId('ntf'),
    userId: DEMO_USER_ID,
    type: 'WEATHER' as NotificationType,
    title: 'Weather update',
    body: 'Light rain expected in the next 3 days. Plan field activities accordingly.',
    link: '/weather',
    isRead: true,
    createdAt: iso(2, 9),
  },
];

export function demoScanResult(
  scanId: string,
  cropName: string,
  condition: string,
  confidence: number,
  severity: Severity,
  isHealthy: boolean,
  symptoms: string[],
  causes: string[],
  actions: string[],
  prevention: string[],
  createdAt: string,
): ScanResult {
  return {
    id: demoId('res'),
    scanId,
    crop: cropName,
    condition,
    isHealthy,
    confidence,
    severity: isHealthy ? null : severity,
    status: isHealthy ? 'HEALTHY' : confidence < 60 ? 'LOW_CONFIDENCE' : 'NEEDS_ATTENTION',
    symptoms,
    causes,
    actions,
    prevention,
    expertHelp:
      'If symptoms continue or the result is uncertain, consult a qualified agricultural expert or your local Krishi Vigyan Kendra before treatment.',
    provider: 'demo',
    isDemo: true,
    createdAt,
  };
}

export { DEMO_LIBRARY };
